// ПОЛНАЯ система переводов для всего сайта (RU/KZ/EN)

const translations = {
    ru: {
        nav_home: 'Главная',
        nav_about: 'О нас',
        nav_news: 'Новости',
        nav_docs: 'Документы',
        nav_leadership: 'Наша команда',
        nav_media: 'Медиа',
        nav_competitions: 'Соревнования',
        nav_sponsor: 'Генеральный спонсор',
        nav_partners: 'Партнёры',
        nav_federations: 'Федерации',
        hero_welcome: 'Добро пожаловать на наш сайт!',
        hero_description_full: 'Наша организация объединяет спортсменов со всего Казахстана. Мы развиваем функциональный фитнес и проводим соревнования по функциональному многоборью. Присоединяйтесь к нашему спортивному сообществу!',
        news_title: 'Последние новости',
        news_subtitle: 'Следите за главными событиями в мире функционального многоборья',
        docs_title: 'Документы',
        docs_subtitle: 'Официальные документы и положения федерации',
        map_title: 'Карта залов',
        map_subtitle: 'Найдите ближайший зал для тренировок по функциональному многоборью в вашем городе',
        about_page_title: 'О нас',
        about_federation_title: 'О Федерации',
        about_federation_text: 'Казахстанская Федерация функционального многоборья (КФФМ) - это республиканское общественное объединение, которое развивает функциональный фитнес и функциональное многоборье на территории Республики Казахстан.',
        about_mission_title: 'Наша миссия',
        about_mission_text: 'Развитие функционального многоборья в Казахстане, популяризация здорового образа жизни и подготовка спортсменов мирового уровня. Мы стремимся сделать функциональный фитнес доступным для каждого казахстанца и создать условия для достижения высоких спортивных результатов.',
        about_goals_title: 'Наши цели',
        about_goal_1: 'Организация и проведение соревнований по функциональному многоборью на всех уровнях',
        about_goal_2: 'Подготовка спортсменов и тренеров высокой квалификации',
        about_goal_3: 'Развитие международного сотрудничества в области функционального фитнеса',
        about_goal_4: 'Популяризация здорового образа жизни среди населения Казахстана',
        leadership_title: 'Наша команда',
        leadership_subtitle: 'Профессионалы, которые развивают спорт в стране',
        leader_name_1: 'Мещеряков Николай Ильич',
        leader_position_1: 'Президент Казахстанской Федерации функционального многоборья.',
        leader_name_2: 'Сулейменов Ерлан Мельсович',
        leader_position_2: 'вице-президент Казахстанской Федерации функционального многоборья, генеральный спонсор, директор КДЛ "Олимп".',
        leader_name_3: 'Лукановский Валентин Владимирович',
        leader_position_3: 'генеральный секретарь, вице-президент Казахстанской Федерации функционального многоборья.',
        leader_name_4: 'Джантлеев Роман Алмасович',
        leader_position_4: 'вице-президент Казахстанской Федерации функционального многоборья.',
        news_winter_cup: 'Зимний Кубок 2025',
        news_crossfit_challenge: 'CrossFit Challenge 2025',
        news_summer_games: 'Summer Games 2025',
        doc_championship_rules: 'Положение чемпионата Казахстана',
        doc_calendar: 'Календарь',
        doc_standards: 'Стандарты',
        doc_antidoping: 'Антидопинг',
        doc_constitution: 'Устав',
        federations_title: 'Международные федерации',
        federations_subtitle: 'Наши партнеры по всему миру',
        btn_more: 'Подробнее',
        btn_back: 'Назад',
        btn_download: 'Скачать',
        btn_view: 'Просмотр',
        footer_rights: '© 2025 Все права защищены — Казахстанская Федерация функционального многоборья',
        footer_info: 'Республиканское общественное объединение «Казахстанская Федерация функционального многоборья» (КФФМ, Functional Fitness Kazakhstan) — официальный руководящий орган по функциональному фитнесу (functional fitness) и функциональному многоборью в Республике Казахстан. Мы развиваем спорт, организуем соревнования и объединяем спортсменов по всему Казахстану.',
        media_title: 'Медиа',
        media_subtitle: 'Фото и видео с наших мероприятий',
        media_gallery_title: 'Фотогалерея',
        media_gallery_subtitle: 'Лучшие моменты наших соревнований',
        competitions_title: 'Соревнования',
        competitions_subtitle: 'Календарь спортивных событий',
        about_welcome_text: 'Добро пожаловать на официальный сайт Федерации функционального многоборья Республики Казахстан! Мы - часть международного спортивного сообщества iF3 и развиваем функциональное многоборье в Казахстане как современное, динамичное и доступное каждому направление, объединяющее людей, стремящихся к силе, выносливости и здоровью.',
        about_mission_desc: 'Популяризация и развитие функционального многоборья в Казахстане',
        about_healthy_nation: 'Здоровая нация',
        about_healthy_nation_desc: 'Формируем культуру движения, силы и выносливости. Продвигаем ценности активного и осознанного образа жизни среди людей всех возрастов - от детей до ветеранов спорта.',
        about_olympic_recognition: 'Олимпийское признание',
        about_olympic_recognition_desc: 'Поддерживаем развитие спорта на международной арене и представляем Казахстан в составе мирового сообщества iF3. Работаем над признанием функционального многоборья как олимпийского вида спорта.',
        about_sport_development: 'Развитие и популяризация спорта',
        about_sport_development_desc: 'Создаём условия для роста спортсменов, проведения национальных и международных турниров, развития спортивных клубов и сообществ по всей стране.',
        about_our_history: 'Наша история',
        about_functional_definition: 'Функциональное многоборье',
        about_functional_desc: 'современный, динамично развивающийся вид спорта, основанный на выполнении функциональных движений с весом собственного тела, свободными отягощениями и циклическими упражнениями. Комплексы выполняются непрерывно на время, что позволяет проверить силу, скорость, координацию, выносливость и устойчивость духа спортсмена.',
        about_main_idea: 'Главная идея функционального многоборья - всестороннее развитие человека, способного проявлять физическую силу, ментальную устойчивость и командный дух в любых условиях. Это спорт, который воспитывает характер и объединяет людей всех возрастов вокруг стремления к здоровью, дисциплине и личному росту.',
        about_federation_creation: 'Создание Федерации',
        about_federation_founding: 'Республиканское общественное объединение «Казахстанская федерация функционального многоборья» было основано 8 сентября 2023 года в городе Астана решением Учредительного съезда.',
        about_leadership: 'Руководство Федерации:',
        about_president: 'Президент: Мещеряков Николай Ильич',
        about_vicepresident_sponsor: 'Вице-президент, Генеральный директор сети КДЛ «Олимп» и Генеральный спонсор Федерации: Сулейменов Ерлан Мельсович',
        about_vicepresident_secretary: 'Вице-президент и Генеральный секретарь: Лукановский Валентин Владимирович',
        about_vicepresident_3: 'Вице-президент: Джантлеев Роман Алмасович',
        about_development_goals: 'Развитие и цели Федерации',
        about_federation_achievement: 'Несмотря на короткий срок существования, Федерация уверенно заявила о себе как о новой спортивной силе Казахстана. Основные направления деятельности:',
        about_healthy_nation_goal: '1. Формирование здоровой нации',
        about_healthy_nation_goal_desc: 'Развитие культуры физической активности, укрепление здоровья и продвижение ценностей спорта среди всех возрастных групп.',
        about_olympic_goal: '2. Олимпийское признание',
        about_olympic_goal_desc: 'Стратегическая цель - включение функционального многоборья в программу Олимпийских игр и представление Казахстана на международной арене.',
        about_sport_goal: '3. Развитие и популяризация спорта',
        about_sport_goal_desc: 'Организация национальных и международных соревнований, укрепление партнёрских связей и создание сильного спортивного сообщества.',
        about_moving_forward: 'Движение вперёд',
        about_moving_forward_desc: 'Федерация активно сотрудничает с Международной федерацией функционального фитнеса (iF3) и продолжает расширять своё присутствие на спортивной карте страны. Функциональное многоборье стремительно набирает популярность в Казахстане, объединяя спортсменов, активных людей и всех, кто выбирает движение, силу и здоровый образ жизни.',
        about_motto: 'Девиз Федерации:',
        about_motto_text: '«Сила. Выносливость. Единство.»',
        
        // News8 - IF3 World Championship 2025 Lithuania
        news8_title: 'Чемпионат мира IF3 2025 — Литва, Вильнюс',
        news8_participants_title: 'Кто участвовал',
        news8_participants_text: 'В Вильнюсе, столице Литвы, с 5 по 7 декабря 2025 года состоялся Чемпионат мира IF3 по функциональному фитнесу, объединивший сильнейших атлетов со всего мира. Национальные федерации IF3 направили своих спортсменов в трёх основных категориях: индивидуальной, юниорской и командной.',
        news8_individual_title: 'Индивидуальные соревнования',
        news8_individual_intro: 'В индивидуальных категориях выступили лучшие мужчины и женщины, отобранные национальными федерациями.',
        news8_individual_quota: 'Каждая страна могла заявить:',
        news8_individual_men: 'до 3 мужчин-индивидуалов,',
        news8_individual_women: 'до 3 женщин-индивидуалов.',
        news8_individual_disciplines: 'Атлеты соревновались в шести дисциплинах, демонстрируя физическую подготовку, технику и стратегию.',
        news8_juniors_title: 'Юниоры',
        news8_juniors_intro: 'Юниорские дивизионы собрали перспективных молодых атлетов из разных стран.',
        news8_juniors_quota: 'Федерации могли заявить:',
        news8_juniors_boys: 'до 3 юниоров,',
        news8_juniors_girls: 'до 3 юниорок в каждой возрастной группе.',
        news8_juniors_importance: 'Выступления юниоров стали важной частью чемпионата, показывая развитие нового поколения спортсменов.',
        news8_teams_title: 'Командные соревнования',
        news8_teams_structure: 'В командных соревнованиях участвовали сборные из 4 атлетов — 2 мужчин и 2 женщин.',
        news8_teams_compete: 'Команды представляли свои страны и соревновались в комплексных тестах, требующих синхронной работы, тактики и высокой командной динамики.',
        news8_geography_title: 'География участников',
        news8_geography_continents: 'На IF3 World Championship 2025 прибыли спортсмены из десятков стран Европы, Азии, Северной и Южной Америки.',
        news8_geography_mix: 'Среди них — как страны с развитой спортивной системой IF3, так и новые федерации, впервые представившие своих атлетов на мировом первенстве.',
        news8_location_title: 'Локация и место проведения',
        news8_location_venue: 'Чемпионат мира IF3 2025 прошёл в Литве, в городе Вильнюс — современном европейском центре спорта и культуры. Соревнования разместились на одной из крупнейших спортивных арен города, оборудованной для мероприятий международного уровня.',
        news8_location_perfect: 'Вильнюс стал идеальной площадкой для проведения мирового первенства: удобная инфраструктура, транспортная доступность, развитая спортивная база и атмосфера исторического центра Европы сделали чемпионат ярким событием для участников и болельщиков.',
        news8_location_enjoy: 'Спортсмены и гости могли насладиться:',
        news8_location_arena: 'комфортом современной арены,',
        news8_location_facilities: 'возможностями для тренировок и восстановления,',
        news8_location_environment: 'уютной городской средой,',
        news8_location_atmosphere: 'красивой старинной архитектурой и зимней атмосферой декабрьского Вильнюса.',
        news8_stats_participants: 'В чемпионате приняли участие 392 атлета из 26 стран.',
        news8_stats_categories: 'Соревнования проводились в следующих категориях:',
        news8_results_title: 'Итоги по странам',
        news8_results_top3: 'Топ-3 стран по количеству призовых мест:',
        news8_results_1st: '🥇 1 место: NORWAY и UNITED KINGDOM (по 8 медалей)',
        news8_results_2nd: '🥈 2 место: FINLAND (7 медалей)',
        news8_results_3rd: '🥉 3 место: SWEDEN и GERMANY (по 4 медали)'
    },
    
    kz: {
        nav_home: 'Басты бет',
        nav_about: 'Біз туралы',
        nav_news: 'Жаңалықтар',
        nav_docs: 'Құжаттар',
        nav_leadership: 'Біздің команда',
        nav_media: 'Медиа',
        nav_competitions: 'Жарыстар',
        nav_sponsor: 'Бас демеуші',
        nav_partners: 'Серіктестер',
        nav_federations: 'Федерациялар',
        hero_welcome: 'Біздің сайтқа қош келдіңіз!',
        hero_description_full: 'Біздің ұйым бүкіл Қазақстаннан спортшыларды біріктіреді. Біз функционалдық фитнесті дамытамыз және функционалдық көпсайыс бойынша жарыстар өткіземіз. Біздің спорттық қауымдастығымызға қосылыңыз!',
        news_title: 'Соңғы жаңалықтар',
        news_subtitle: 'Функционалдық көпсайыс әлеміндегі басты оқиғаларды қадағалаңыз',
        docs_title: 'Құжаттар',
        docs_subtitle: 'Федерацияның ресми құжаттары мен ережелері',
        map_title: 'Залдар картасы',
        map_subtitle: 'Сіздің қалаңызда функционалдық көпсайыс бойынша жаттығуға ең жақын залды табыңыз',
        about_page_title: 'Біз туралы',
        about_federation_title: 'Федерация туралы',
        about_federation_text: 'Қазақстандық функционалдық көпсайыс федерациясы (ҚФКФ) - Қазақстан Республикасының аумағында функционалдық фитнес пен функционалдық көпсайысты дамытатын республикалық қоғамдық бірлестік.',
        about_mission_title: 'Біздің миссиямыз',
        about_mission_text: 'Қазақстанда функционалдық көпсайысты дамыту, салауатты өмір салтын насихаттау және әлемдік деңгейдегі спортшыларды даярлау. Біз функционалдық фитнесті әрбір қазақстандық үшін қолжетімді ету және жоғары спорттық нәтижелерге жету үшін жағдай жасауға ұмтыламыз.',
        about_goals_title: 'Біздің мақсаттарымыз',
        about_goal_1: 'Барлық деңгейлерде функционалдық көпсайыс бойынша жарыстарды ұйымдастыру және өткізу',
        about_goal_2: 'Жоғары білікті спортшылар мен жаттықтырушыларды даярлау',
        about_goal_3: 'Функционалдық фитнес саласында халықаралық ынтымақтастықты дамыту',
        about_goal_4: 'Қазақстан халқы арасында салауатты өмір салтын насихаттау',
        leadership_title: 'Біздің команда',
        leadership_subtitle: 'Елде спортты дамытатын кәсіпқойлар',
        leader_name_1: 'Мещеряков Николай Ильич',
        leader_position_1: 'Қазақстандық функционалдық көпсайыс федерациясының президенті.',
        leader_name_2: 'Сүлейменов Ерлан Мелсұлы',
        leader_position_2: 'Қазақстандық функционалдық көпсайыс федерациясының вице-президенті, бас демеуші, КДЛ "Олимп" директоры.',
        leader_name_3: 'Лукановский Валентин Владимирович',
        leader_position_3: 'бас хатшы, Қазақстандық функционалдық көпсайыс федерациясының вице-президенті.',
        leader_name_4: 'Жантілеев Роман Алмасұлы',
        leader_position_4: 'Қазақстандық функционалдық көпсайыс федерациясының вице-президенті.',
        news_winter_cup: 'Қысқы Кубок 2025',
        news_crossfit_challenge: 'CrossFit Challenge 2025',
        news_summer_games: 'Summer Games 2025',
        doc_championship_rules: 'Қазақстан чемпионаты ережесі',
        doc_calendar: 'Күнтізбе',
        doc_standards: 'Стандарттар',
        doc_antidoping: 'Антидопинг',
        doc_constitution: 'Жарғы',
        federations_title: 'Халықаралық федерациялар',
        federations_subtitle: 'Әлем бойынша біздің серіктестеріміз',
        btn_more: 'Толығырақ',
        btn_back: 'Артқа',
        btn_download: 'Жүктеп алу',
        btn_view: 'Қарау',
        footer_rights: '© 2025 Барлық құқықтар қорғалған — Қазақстандық функционалдық көпсайыс федерациясы',
        footer_info: '«Қазақстандық функционалдық көпсайыс федерациясы» республикалық қоғамдық бірлестігі (ҚФКФ, Functional Fitness Kazakhstan) — Қазақстан Республикасындағы функционалдық фитнес (functional fitness) және функционалдық көпсайыс бойынша ресми басқарушы орган. Біз спортты дамытамыз, жарыстар ұйымдастырамыз және бүкіл Қазақстан бойынша спортшыларды біріктіреміз.',
        media_title: 'Медиа',
        media_subtitle: 'Біздің іс-шараларымыздан фото және видео',
        media_gallery_title: 'Фотогалерея',
        media_gallery_subtitle: 'Біздің жарыстарымыздың үздік сәттері',
        competitions_title: 'Жарыстар',
        competitions_subtitle: 'Спорттық оқиғалар күнтізбесі',
        about_welcome_text: 'Қазақстан Республикасының функционалдық көпсайыс федерациясының ресми сайтына қош келдіңіз! Біз халықаралық спорттық қауымдастық iF3-тің бір бөлігіміз және Қазақстанда функционалдық көпсайысты қазіргі заманғы, серпінді және әркімге қолжетімді бағыт ретінде дамытамыз, күш, төзімділік және денсаулыққа ұмтылатын адамдарды біріктіреміз.',
        about_mission_desc: 'Қазақстанда функционалдық көпсайысты насихаттау және дамыту',
        about_healthy_nation: 'Салауатты ұлт',
        about_healthy_nation_desc: 'Қозғалыс, күш және төзімділік мәдениетін қалыптастырамыз. Барлық жастағы адамдар арасында - балалардан спорт ардагерлеріне дейін белсенді және саналы өмір салтының құндылықтарын насихаттаймыз.',
        about_olympic_recognition: 'Олимпиадалық тану',
        about_olympic_recognition_desc: 'Халықаралық аренада спортты дамытуды қолдаймыз және Қазақстанды әлемдік qF3 қауымдастығының құрамында ұсынамыз. Функционалдық көпсайысты олимпиадалық спорт түрі ретінде тану үшін жұмыс жасаймыз.',
        about_sport_development: 'Спортты дамыту және насихаттау',
        about_sport_development_desc: 'Спортшылардың өсуі, ұлттық және халықаралық турнирлер өткізу, бүкіл ел бойынша спорт клубтары мен қауымдастықтарды дамыту үшін жағдайлар жасаймыз.',
        about_our_history: 'Біздің тарихымыз',
        about_functional_definition: 'Функционалдық көпсайыс',
        about_functional_desc: 'өз денесінің салмағымен, еркін ауырлықтармен және циклдік жаттығулармен функционалдық қозғалыстарды орындауға негізделген қазіргі заманғы, серпінді дамып жатқан спорт түрі. Кешендер үздіксіз уақытқа орындалады, бұл спортшының күшін, жылдамдығын, үйлесімділігін, төзімділігін және рух тұрақтылығын тексеруге мүмкіндік береді.',
        about_main_idea: 'Функционалдық көпсайыстың басты идеясы - кез келген жағдайда физикалық күш, ақыл-ой тұрақтылығы және командалық рухты көрсете алатын адамды жан-жақты дамыту. Бұл мінезді тәрбиелейтін және барлық жастағы адамдарды денсаулық, тәртіп және жеке өсу ұмтылысы төңірегінде біріктіретін спорт.',
        about_federation_creation: 'Федерацияны құру',
        about_federation_founding: '«Қазақстандық функционалдық көпсайыс федерациясы» республикалық қоғамдық бірлестігі 2023 жылдың 8 қыркүйегінде Астана қаласында Құрылтай съезінің шешімімен құрылды.',
        about_leadership: 'Федерация басшылығы:',
        about_president: 'Президент: Мещеряков Николай Ильич',
        about_vicepresident_sponsor: 'Вице-президент, КДЛ «Олимп» желісінің бас директоры және Федерацияның бас демеушісі: Сүлейменов Ерлан Мелсұлы',
        about_vicepresident_secretary: 'Вице-президент және бас хатшы: Лукановский Валентин Владимирович',
        about_vicepresident_3: 'Вице-президент: Жантілеев Роман Алмасұлы',
        about_development_goals: 'Федерацияның дамуы мен мақсаттары',
        about_federation_achievement: 'Қысқа мерзімде болғанына қарамастан, Федерация Қазақстанның жаңа спорттық күші ретінде өзін сенімді түрде көрсетті. Негізгі қызмет бағыттары:',
        about_healthy_nation_goal: '1. Салауатты ұлтты қалыптастыру',
        about_healthy_nation_goal_desc: 'Барлық жас топтарында физикалық белсенділік мәдениетін дамыту, денсаулықты нығайту және спорт құндылықтарын насихаттау.',
        about_olympic_goal: '2. Олимпиадалық тану',
        about_olympic_goal_desc: 'Стратегиялық мақсат - функционалдық көпсайысты Олимпиада ойындарының бағдарламасына енгізу және Қазақстанды халықаралық аренада ұсыну.',
        about_sport_goal: '3. Спортты дамыту және насихаттау',
        about_sport_goal_desc: 'Ұлттық және халықаралық жарыстарды ұйымдастыру, серіктестік байланыстарды нығайту және күшті спорттық қауымдастық құру.',
        about_moving_forward: 'Алға қарай қозғалыс',
        about_moving_forward_desc: 'Федерация Халықаралық функционалдық фитнес федерациясымен (iF3) белсенді ынтымақтасады және елдің спорттық картасында өз қатысуын кеңейтуді жалғастырады. Функционалдық көпсайыс Қазақстанда тез әрі танымал бола бастады, спортшыларды, белсенді адамдарды және қозғалысты, күшті және салауатты өмір салтын таңдайтындардың барлығын біріктіреді.',
        about_motto: 'Федерацияның ұраны:',
        about_motto_text: '«Күш. Төзімділік. Бірлік.»',
        
        // News8 - IF3 World Championship 2025 Lithuania
        news8_title: 'IF3 әлем чемпионаты 2025 — Литва, Вильнюс',
        news8_participants_title: 'Кім қатысты',
        news8_participants_text: 'Литваның астанасы Вильнюста, 2025 жылдың 5-7 желтоқсанында бүкіл әлемнен ең күшті атлеттерді біріктірген функционалдық фитнес бойынша IF3 әлем чемпионаты өтті. IF3 ұлттық федерациялары өз спортшыларын үш негізгі санатта жіберді: жеке, жасөспірімдер және командалық.',
        news8_individual_title: 'Жеке жарыстар',
        news8_individual_intro: 'Жеке санаттарда ұлттық федерациялар іріктеген үздік ер адамдар мен әйелдер өнер көрсетті.',
        news8_individual_quota: 'Әр ел мыналарды мәлімдей алды:',
        news8_individual_men: '3-ке дейін жеке ер адамдар,',
        news8_individual_women: '3-ке дейін жеке әйелдер.',
        news8_individual_disciplines: 'Атлеттер алты пәнде бәсекелесіп, физикалық дайындық, техника және стратегияны көрсетті.',
        news8_juniors_title: 'Жасөспірімдер',
        news8_juniors_intro: 'Жасөспірімдер дивизиондары әр түрлі елдерден келе жатқан перспективалы жас атлеттерді жинады.',
        news8_juniors_quota: 'Федерациялар мәлімдей алды:',
        news8_juniors_boys: '3-ке дейін жасөспірімдер,',
        news8_juniors_girls: 'әр жас тобында 3-ке дейін жасөспірім қыздар.',
        news8_juniors_importance: 'Жасөспірімдердің өнер көрсетулері чемпионаттың маңызды бөлігі болды, спортшылардың жаңа ұрпағының дамуын көрсетті.',
        news8_teams_title: 'Командалық жарыстар',
        news8_teams_structure: 'Командалық жарыстарда 4 атлеттен — 2 ер адам және 2 әйелден тұратын құрамалар қатысты.',
        news8_teams_compete: 'Командалар өз елдерін өкілдік етті және синхронды жұмыс, тактика және жоғары командалық динамиканы талап ететін кешенді тесттерде бәсекелесті.',
        news8_geography_title: 'Қатысушылардың географиясы',
        news8_geography_continents: 'IF3 World Championship 2025-ке Еуропа, Азия, Солтүстік және Оңтүстік Американың ондаған елдерінен спортшылар келді.',
        news8_geography_mix: 'Олардың арасында — IF3 дамыған спорттық жүйесі бар елдер де, әлемдік бірінші рет өз атлеттерін көрсеткен жаңа федерациялар да бар.',
        news8_location_title: 'Орналасқан жері және өткізілу орны',
        news8_location_venue: 'IF3 әлем чемпионаты 2025 Литвада, Вильнюс қаласында — заманауи еуропалық спорт және мәдениет орталығында өтті. Жарыстар халықаралық деңгейдегі іс-шаралар үшін жабдықталған қаланың ең ірі спорт аренасының бірінде орналасты.',
        news8_location_perfect: 'Вильнюс әлемдік бірінші рет өткізуге өте жарамды алаң болды: ыңғайлы инфрақұрылым, көлік қолжетімділігі, дамыған спорттық база және Еуропаның тарихи орталығының атмосферасы чемпионатты қатысушылар мен жанкүйерлер үшін жарқын оқиғаға айналдырды.',
        news8_location_enjoy: 'Спортшылар мен қонақтар мынадан ләззат ала алды:',
        news8_location_arena: 'заманауи арена жайлылығы,',
        news8_location_facilities: 'жаттығу және қалпына келтіру мүмкіндіктері,',
        news8_location_environment: 'жайлы қалалық орта,',
        news8_location_atmosphere: 'әдемі ескі сәулет және желтоқсан айындағы Вильнюстың қысқы атмосферасы.',
        news8_stats_participants: 'Чемпионатқа 26 елден 392 атлет қатысты.',
        news8_stats_categories: 'Жарыстар келесі санаттарда өткізілді:',
        news8_results_title: 'Елдер бойынша қорытындылар',
        news8_results_top3: 'Жүлделі орындар саны бойынша топ-3 ел:',
        news8_results_1st: '🥇 1 орын: NORWAY және UNITED KINGDOM (әрқайсысы 8 медаль)',
        news8_results_2nd: '🥈 2 орын: FINLAND (7 медаль)',
        news8_results_3rd: '🥉 3 орын: SWEDEN және GERMANY (әрқайсысы 4 медаль)'
    },
    
    en: {
        nav_home: 'Home',
        nav_about: 'About',
        nav_news: 'News',
        nav_docs: 'Documents',
        nav_leadership: 'Our Team',
        nav_media: 'Media',
        nav_competitions: 'Competitions',
        nav_sponsor: 'General Sponsor',
        nav_partners: 'Partners',
        nav_federations: 'Federations',
        hero_welcome: 'Welcome to our website!',
        hero_description_full: 'Our organization unites athletes from all over Kazakhstan. We develop functional fitness and conduct functional pentathlon competitions. Join our sports community!',
        news_title: 'Latest News',
        news_subtitle: 'Stay updated with the main events in the world of functional fitness',
        docs_title: 'Documents',
        docs_subtitle: 'Official documents and regulations of the federation',
        map_title: 'Gym Map',
        map_subtitle: 'Find the nearest functional fitness gym in your city',
        about_page_title: 'About Us',
        about_federation_title: 'About Federation',
        about_federation_text: 'Kazakhstan Functional Fitness Federation (KFFF) is a republican public association that develops functional fitness and functional pentathlon in the Republic of Kazakhstan.',
        about_mission_title: 'Our Mission',
        about_mission_text: 'Development of functional fitness in Kazakhstan, promotion of a healthy lifestyle and training of world-class athletes. We strive to make functional fitness accessible to every Kazakhstani and create conditions for achieving high sports results.',
        about_goals_title: 'Our Goals',
        about_goal_1: 'Organization and conduct of functional fitness competitions at all levels',
        about_goal_2: 'Training of highly qualified athletes and coaches',
        about_goal_3: 'Development of international cooperation in the field of functional fitness',
        about_goal_4: 'Promotion of healthy lifestyle among the population of Kazakhstan',
        leadership_title: 'Our Team',
        leadership_subtitle: 'Professionals who develop sports in the country',
        leader_name_1: 'Meshcheryakov Nikolay Ilyich',
        leader_position_1: 'President of the Kazakhstan Functional Fitness Federation.',
        leader_name_2: 'Suleimenov Yerlan Melsovich',
        leader_position_2: 'Vice President of the Kazakhstan Functional Fitness Federation, General Sponsor, Director of CDL "Olymp".',
        leader_name_3: 'Lukanovsky Valentin Vladimirovich',
        leader_position_3: 'General Secretary, Vice President of the Kazakhstan Functional Fitness Federation.',
        leader_name_4: 'Dzhantleev Roman Almasovich',
        leader_position_4: 'Vice President of the Kazakhstan Functional Fitness Federation.',
        news_winter_cup: 'Winter Cup 2025',
        news_crossfit_challenge: 'CrossFit Challenge 2025',
        news_summer_games: 'Summer Games 2025',
        doc_championship_rules: 'Kazakhstan Championship Regulations',
        doc_calendar: 'Calendar',
        doc_standards: 'Standards',
        doc_antidoping: 'Anti-Doping',
        doc_constitution: 'Constitution',
        federations_title: 'International Federations',
        federations_subtitle: 'Our partners around the world',
        btn_more: 'Read More',
        btn_back: 'Back',
        btn_download: 'Download',
        btn_view: 'View',
        footer_rights: '© 2025 All rights reserved — Kazakhstan Functional Fitness Federation',
        footer_info: 'Republican Public Association "Kazakhstan Functional Fitness Federation" (KFFF, Functional Fitness Kazakhstan) is the official governing body for functional fitness and functional pentathlon in the Republic of Kazakhstan. We develop sport, organize competitions and unite athletes throughout Kazakhstan.',
        media_title: 'Media',
        media_subtitle: 'Photos and videos from our events',
        media_gallery_title: 'Photo Gallery',
        media_gallery_subtitle: 'Best moments from our competitions',
        competitions_title: 'Competitions',
        competitions_subtitle: 'Sports events calendar',
        about_welcome_text: 'Welcome to the official website of the Functional Fitness Federation of the Republic of Kazakhstan! We are part of the international sports community iF3 and develop functional fitness in Kazakhstan as a modern, dynamic and accessible direction that unites people striving for strength, endurance and health.',
        about_mission_desc: 'Promotion and development of functional fitness in Kazakhstan',
        about_healthy_nation: 'Healthy Nation',
        about_healthy_nation_desc: 'We form a culture of movement, strength and endurance. We promote the values of an active and conscious lifestyle among people of all ages - from children to sports veterans.',
        about_olympic_recognition: 'Olympic Recognition',
        about_olympic_recognition_desc: 'We support the development of sport in the international arena and represent Kazakhstan as part of the world community iF3. We are working on the recognition of functional fitness as an Olympic sport.',
        about_sport_development: 'Development and Promotion of Sport',
        about_sport_development_desc: 'We create conditions for the growth of athletes, national and international tournaments, development of sports clubs and communities throughout the country.',
        about_our_history: 'Our History',
        about_functional_definition: 'Functional Fitness',
        about_functional_desc: 'a modern, dynamically developing sport based on performing functional movements with bodyweight, free weights and cyclical exercises. Complexes are performed continuously for time, which allows to test the strength, speed, coordination, endurance and mental resilience of the athlete.',
        about_main_idea: 'The main idea of functional fitness is the comprehensive development of a person capable of showing physical strength, mental resilience and team spirit in any conditions. This is a sport that builds character and unites people of all ages around the pursuit of health, discipline and personal growth.',
        about_federation_creation: 'Creation of the Federation',
        about_federation_founding: 'The Republican Public Association "Kazakhstan Functional Fitness Federation" was founded on September 8, 2023 in Astana by the decision of the Founding Congress.',
        about_leadership: 'Federation Leadership:',
        about_president: 'President: Meshcheryakov Nikolay Ilyich',
        about_vicepresident_sponsor: 'Vice President, General Director of CDL "Olymp" network and General Sponsor of the Federation: Suleimenov Yerlan Melsovich',
        about_vicepresident_secretary: 'Vice President and General Secretary: Lukanovsky Valentin Vladimirovich',
        about_vicepresident_3: 'Vice President: Dzhantleev Roman Almasovich',
        about_development_goals: 'Development and Goals of the Federation',
        about_federation_achievement: 'Despite its short existence, the Federation has confidently established itself as a new sporting force in Kazakhstan. Main activities:',
        about_healthy_nation_goal: '1. Formation of a Healthy Nation',
        about_healthy_nation_goal_desc: 'Development of physical activity culture, health promotion and promotion of sports values among all age groups.',
        about_olympic_goal: '2. Olympic Recognition',
        about_olympic_goal_desc: 'Strategic goal - inclusion of functional fitness in the Olympic Games program and representation of Kazakhstan in the international arena.',
        about_sport_goal: '3. Development and Promotion of Sport',
        about_sport_goal_desc: 'Organization of national and international competitions, strengthening of partnerships and creation of a strong sports community.',
        about_moving_forward: 'Moving Forward',
        about_moving_forward_desc: 'The Federation actively cooperates with the International Functional Fitness Federation (iF3) and continues to expand its presence on the sports map of the country. Functional fitness is rapidly gaining popularity in Kazakhstan, uniting athletes, active people and everyone who chooses movement, strength and a healthy lifestyle.',
        about_motto: 'Federation Motto:',
        about_motto_text: '"Strength. Endurance. Unity."',
        
        // News8 - IF3 World Championship 2025 Lithuania
        news8_title: 'IF3 World Championship 2025 — Lithuania, Vilnius',
        news8_participants_title: 'Participants',
        news8_participants_text: 'The IF3 World Championship in functional fitness took place in Vilnius, the capital of Lithuania, from December 5-7, 2025, bringing together the strongest athletes from around the world. National IF3 federations sent their athletes in three main categories: individual, junior, and team.',
        news8_individual_title: 'Individual Competitions',
        news8_individual_intro: 'The individual categories featured the best men and women selected by national federations.',
        news8_individual_quota: 'Each country could register:',
        news8_individual_men: 'up to 3 individual men,',
        news8_individual_women: 'up to 3 individual women.',
        news8_individual_disciplines: 'Athletes competed in six disciplines, demonstrating physical fitness, technique, and strategy.',
        news8_juniors_title: 'Juniors',
        news8_juniors_intro: 'Junior divisions gathered promising young athletes from different countries.',
        news8_juniors_quota: 'Federations could register:',
        news8_juniors_boys: 'up to 3 junior boys,',
        news8_juniors_girls: 'up to 3 junior girls in each age group.',
        news8_juniors_importance: 'Junior performances became an important part of the championship, showing the development of a new generation of athletes.',
        news8_teams_title: 'Team Competitions',
        news8_teams_structure: 'Team competitions included teams of 4 athletes — 2 men and 2 women.',
        news8_teams_compete: 'Teams represented their countries and competed in complex tests requiring synchronized work, tactics, and high team dynamics.',
        news8_geography_title: 'Participant Geography',
        news8_geography_continents: 'Athletes from dozens of countries in Europe, Asia, North and South America arrived at the IF3 World Championship 2025.',
        news8_geography_mix: 'Among them were both countries with developed IF3 sports systems and new federations presenting their athletes at the world championship for the first time.',
        news8_location_title: 'Location and Venue',
        news8_location_venue: 'The IF3 World Championship 2025 took place in Lithuania, in the city of Vilnius — a modern European center of sports and culture. The competitions were hosted at one of the city\'s largest sports arenas, equipped for international-level events.',
        news8_location_perfect: 'Vilnius became an ideal venue for the world championship: convenient infrastructure, transport accessibility, developed sports facilities, and the atmosphere of a historical European center made the championship a bright event for participants and fans.',
        news8_location_enjoy: 'Athletes and guests could enjoy:',
        news8_location_arena: 'the comfort of a modern arena,',
        news8_location_facilities: 'training and recovery facilities,',
        news8_location_environment: 'a cozy urban environment,',
        news8_location_atmosphere: 'beautiful old architecture and the winter atmosphere of December Vilnius.',
        news8_stats_participants: 'The championship featured 392 athletes from 26 countries.',
        news8_stats_categories: 'Competitions were held in the following categories:',
        news8_results_title: 'Results by Country',
        news8_results_top3: 'Top 3 countries by number of medals:',
        news8_results_1st: '🥇 1st place: NORWAY and UNITED KINGDOM (8 medals each)',
        news8_results_2nd: '🥈 2nd place: FINLAND (7 medals)',
        news8_results_3rd: '🥉 3rd place: SWEDEN and GERMANY (4 medals each)'
    }
};

// Функция перевода страницы
function translatePage(lang) {
    const elements = document.querySelectorAll('[data-translate]');
    elements.forEach(element => {
        const key = element.getAttribute('data-translate');
        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
    
    // Сохраняем выбранный язык
    localStorage.setItem('selectedLanguage', lang);
    
    // Обновляем отображение текущего языка
    const currentLangDisplay = document.getElementById('currentLang');
    if (currentLangDisplay) {
        currentLangDisplay.textContent = lang.toUpperCase();
    }
    
    // Обновляем активный пункт в выпадающем меню
    document.querySelectorAll('.language-option').forEach(option => {
        option.classList.remove('active');
        if (option.getAttribute('data-lang') === lang) {
            option.classList.add('active');
        }
    });
}

// Инициализация переключателя языков
document.addEventListener('DOMContentLoaded', () => {
    const languageBtn = document.getElementById('languageBtn');
    const languageDropdown = document.getElementById('languageDropdown');
    const languageOptions = document.querySelectorAll('.language-option');

    // Открытие/закрытие выпадающего меню
    if (languageBtn) {
        languageBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            languageDropdown.classList.toggle('active');
        });
    }

    // Выбор языка
    languageOptions.forEach(option => {
        option.addEventListener('click', () => {
            const lang = option.getAttribute('data-lang');
            translatePage(lang);
            languageDropdown.classList.remove('active');
        });
    });

    // Закрытие меню при клике вне его
    document.addEventListener('click', (e) => {
        if (!e.target.closest('.language-switcher')) {
            if (languageDropdown) {
                languageDropdown.classList.remove('active');
            }
        }
    });

    // Загрузка сохраненного языка при загрузке страницы
    const savedLang = localStorage.getItem('selectedLanguage') || 'ru';
    translatePage(savedLang);
});
